Makefile:
Filtering the two object files isn't enough on my system; $(SRCS1)
also has to be filtered.

$(DEPDIR)/src needs to exist now that the *.cpp files are in the src/
subdir.

Now, 'make -k' fails with the following.

[...]
In file included from src/Task.cpp:9:
src/Worktodo.h: In static member function 'static Task Worktodo::makePM1(Args&, u32)':
src/Worktodo.h:22:39: error: no matching function for call to 'Task::Task(Task::Kind, u32&, Args&)'
   22 |    Task task(Task::PM1, exponent, args);
      |                                       ^
In file included from src/Task.cpp:3:
src/Task.h:16:8: note: candidate: 'Task::Task()'
   16 | struct Task {
      |        ^~~~
src/Task.h:16:8: note:   candidate expects 0 arguments, 3 provided
src/Task.h:16:8: note: candidate: 'Task::Task(const Task&)'
src/Task.h:16:8: note:   candidate expects 1 argument, 3 provided
src/Task.h:16:8: note: candidate: 'Task::Task(Task&&)'
src/Task.h:16:8: note:   candidate expects 1 argument, 3 provided
In file included from src/Task.cpp:9:
src/Worktodo.h: In static member function 'static Task Worktodo::makeLL(Args&, u32)':
src/Worktodo.h:26:68: error: 'LL' is not a member of 'Task'
   26 |   static Task makeLL(Args& args, u32 exponent) { return Task(Task::LL, exponent); }
      |                                                                    ^~
src/Worktodo.h: In static member function 'static Task Worktodo::makeVerify(Args&, std::string)':
src/Worktodo.h:27:83: error: no matching function for call to 'Task::Task(Task::Kind, std::string&)'
   27 |   static Task makeVerify(Args& args, string path) { return Task(Task::VERIFY, path); }
      |                                                                                   ^
In file included from src/Task.cpp:3:
src/Task.h:16:8: note: candidate: 'Task::Task()'
   16 | struct Task {
      |        ^~~~
src/Task.h:16:8: note:   candidate expects 0 arguments, 2 provided
src/Task.h:16:8: note: candidate: 'Task::Task(const Task&)'
src/Task.h:16:8: note:   candidate expects 1 argument, 2 provided
src/Task.h:16:8: note: candidate: 'Task::Task(Task&&)'
src/Task.h:16:8: note:   candidate expects 1 argument, 2 provided